### ISSUE TITLE
Setup wizard when no settings are detected

### ISSUE THREAD

**Issue by makuto** [makuto/Liked-Saved-Image-Downloader#46]
Related to #36, but not necessarily the same (i.e. we could do #36 without doing this issue).

Make a nice step-by-step wizard for setting up:

- [ ] Output directory location
- [ ] Initial directory provider(s)
- [ ] Downloader APIs
- [ ] Script auto-run timing (#45)
- [ ] Throttle downloading setting (#44)
- [ ] Login/HTTPS (stretch, could also be covered by #38)
